version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: 
      context: ./backend
    ports:
      - "4000:4000"